"""drop_user_price_snapshots_table

Revision ID: d031d7ddb44d
Revises: 62578e8d672d
Create Date: 2026-03-11 00:10:28.710096

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d031d7ddb44d"
down_revision: str | Sequence[str] | None = "62578e8d672d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_user_price_snapshots_symbol"), table_name="user_price_snapshots")
    op.drop_index(op.f("idx_user_price_snapshots_user_id"), table_name="user_price_snapshots")
    op.drop_table("user_price_snapshots")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_price_snapshots",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("symbol", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("price", sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id", "symbol", name=op.f("user_price_snapshots_pkey")),
    )
    op.create_index(
        op.f("idx_user_price_snapshots_user_id"), "user_price_snapshots", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_user_price_snapshots_symbol"), "user_price_snapshots", ["symbol"], unique=False
    )
    # ### end Alembic commands ###
