"""initial schema

Revision ID: ebccb9690eee
Revises:
Create Date: 2026-03-05 17:07:00.413694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebccb9690eee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("direction", sa.String(length=5), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("tp1_level", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sl_level", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("rr_ratio", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("atr_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("timeframe", sa.String(length=5), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tp1_hit", sa.Boolean(), nullable=True),
        sa.Column("tp1_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sl_moved_to_breakeven", sa.Boolean(), nullable=True),
        sa.Column("close_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("close_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.String(length=15), nullable=True),
        sa.Column("pnl_usdt", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("pnl_percent", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("supertrend_exit", sa.Boolean(), nullable=True),
        sa.Column("ai_context", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="NOW()", nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="NOW()", nullable=True),
        sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name="signals_direction_check"),
        sa.CheckConstraint(
            "status IN ('EMITIDA', 'TOMADA', 'CERRADA', 'CANCELADA')", name="signals_status_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_config",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("capital_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("risk_percent", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("max_drawdown_percent", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("timeframe_primary", sa.String(length=5), nullable=True),
        sa.Column("setup_completed", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="NOW()", nullable=True),
        sa.CheckConstraint(
            "direction IN ('LONG', 'SHORT', 'AMBOS')", name="user_config_direction_check"
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "active_trades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=5), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tp1_level", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("sl_level", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="NOW()", nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="NOW()", nullable=True),
        sa.CheckConstraint("direction IN ('LONG', 'SHORT')", name="active_trades_direction_check"),
        sa.CheckConstraint(
            "status IN ('ABIERTO', 'CERRADO', 'PAUSADO')", name="active_trades_status_check"
        ),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "drawdown_tracker",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("current_drawdown_usdt", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("current_drawdown_percent", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("losses_count", sa.Integer(), nullable=True),
        sa.Column("last_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_paused", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="NOW()", nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user_config.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drawdown_tracker")
    op.drop_table("active_trades")
    op.drop_table("user_config")
    op.drop_table("signals")
    # ### end Alembic commands ###
